// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProphetProfiler.Api.Data;

#nullable disable

namespace ProphetProfiler.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209144905_AddBetTypeAndPoints")]
    partial class AddBetTypeAndPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("GameSessionPlayer", b =>
                {
                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantsId", "SessionsId");

                    b.HasIndex("SessionsId");

                    b.ToTable("SessionParticipants", (string)null);
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BettorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoBet")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PredictedWinnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BettorId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PredictedWinnerId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.BoardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AverageDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.GameProfile", b =>
                {
                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Aggressivity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Analysis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bluff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Patience")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardGameId");

                    b.ToTable("GameProfiles");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardGameId");

                    b.HasIndex("WinnerId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.PlayerProfile", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Aggressivity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Analysis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bluff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Patience")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerProfile_Aggressivity", "[Aggressivity] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_PlayerProfile_Analysis", "[Analysis] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_PlayerProfile_Bluff", "[Bluff] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_PlayerProfile_Patience", "[Patience] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BetsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("OraclePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBetsPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "BoardGameId");

                    b.HasIndex("BoardGameId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("GameSessionPlayer", b =>
                {
                    b.HasOne("ProphetProfiler.Api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProphetProfiler.Api.Models.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.Bet", b =>
                {
                    b.HasOne("ProphetProfiler.Api.Models.Player", "Bettor")
                        .WithMany()
                        .HasForeignKey("BettorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProphetProfiler.Api.Models.GameSession", "GameSession")
                        .WithMany("Bets")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProphetProfiler.Api.Models.Player", null)
                        .WithMany("Bets")
                        .HasForeignKey("PlayerId");

                    b.HasOne("ProphetProfiler.Api.Models.Player", "PredictedWinner")
                        .WithMany()
                        .HasForeignKey("PredictedWinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bettor");

                    b.Navigation("GameSession");

                    b.Navigation("PredictedWinner");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.GameProfile", b =>
                {
                    b.HasOne("ProphetProfiler.Api.Models.BoardGame", "BoardGame")
                        .WithOne("Profile")
                        .HasForeignKey("ProphetProfiler.Api.Models.GameProfile", "BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.GameSession", b =>
                {
                    b.HasOne("ProphetProfiler.Api.Models.BoardGame", "BoardGame")
                        .WithMany("Sessions")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProphetProfiler.Api.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoardGame");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.PlayerProfile", b =>
                {
                    b.HasOne("ProphetProfiler.Api.Models.Player", null)
                        .WithOne("Profile")
                        .HasForeignKey("ProphetProfiler.Api.Models.PlayerProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.PlayerStats", b =>
                {
                    b.HasOne("ProphetProfiler.Api.Models.BoardGame", "BoardGame")
                        .WithMany()
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProphetProfiler.Api.Models.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.BoardGame", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.GameSession", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("ProphetProfiler.Api.Models.Player", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
